services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./downloads:/app/downloads
    env_file:
      - .env
    environment:
      INSTAGRAM_LOG_RAW: "true"
      UVICORN_LOG_LEVEL: "debug"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    restart: unless-stopped
